### ISSUE TITLE
problems while executing

### ISSUE THREAD

**Issue by juancresc** [maxolasersquad/orthosie#36]
Installed everything in ubuntu but I got this:
```
python3 manage.py makemigrations
Traceback (most recent call last):
  File "manage.py", line 10, in <module>
    execute_from_command_line(sys.argv)
  File "/vagrant/www/orthosie/venv/lib/python3.4/site-packages/django/core/management/__init__.py", line 371, in execute_from_command_line
    utility.execute()
  File "/vagrant/www/orthosie/venv/lib/python3.4/site-packages/django/core/management/__init__.py", line 347, in execute
    django.setup()
  File "/vagrant/www/orthosie/venv/lib/python3.4/site-packages/django/__init__.py", line 24, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "/vagrant/www/orthosie/venv/lib/python3.4/site-packages/django/apps/registry.py", line 112, in populate
    app_config.import_models()
  File "/vagrant/www/orthosie/venv/lib/python3.4/site-packages/django/apps/config.py", line 198, in import_models
    self.models_module = import_module(models_module_name)
  File "/vagrant/www/orthosie/venv/lib/python3.4/importlib/__init__.py", line 109, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 2254, in _gcd_import
  File "<frozen importlib._bootstrap>", line 2237, in _find_and_load
  File "<frozen importlib._bootstrap>", line 2226, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 1200, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 1129, in _exec
  File "<frozen importlib._bootstrap>", line 1471, in exec_module
  File "<frozen importlib._bootstrap>", line 321, in _call_with_frames_removed
  File "/vagrant/www/orthosie/register/models.py", line 75, in <module>
    class Transaction(models.Model):
  File "/vagrant/www/orthosie/register/models.py", line 76, in Transaction
    shift = models.ForeignKey(Shift)
TypeError: __init__() missing 1 required positional argument: 'on_delete'
```

**Comment by juancresc** [comment]
I've changed in requirements file to 
django==1.10

but now I get 
```

AssertionError at /shifts/
("Creating a ModelSerializer without either the 'fields' attribute or the 'exclude' attribute has been deprecated since 3.3.0, and is now disallowed. Add an explicit fields = '__all__' to the ShiftSerializer serializer.",)

```
while running

**Comment by maxolasersquad** [comment]
Hi @juanmas07 . At this time I don't have the spare time to really support this project. I do have plan to get back in the game, but it will be a few more months.
